name: Build OGX-Mini

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board:
          - PI_PICO2W

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: false

      - name: Setup ARM Toolchain (Fast CDN)
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '13.3.Rel1'

      - name: Install Python Cryptography
        run: |
          python3 -m pip install --break-system-packages pycryptodome

      - name: Get Pico SDK (Shallow)
        run: |
          git clone --depth 1 --branch 2.1.0 --recurse-submodules --shallow-submodules https://github.com/raspberrypi/pico-sdk.git

      - name: Fetch Required Submodules
        run: |
          git submodule update --init Firmware/external/tinyusb
          git submodule update --init Firmware/external/Pico-PIO-USB
          git submodule update --init Firmware/external/bluepad32
          git submodule update --init Firmware/external/libfixmath

          # Enter bluepad32 to fetch its internal BTstack submodule
          cd Firmware/external/bluepad32
          git submodule update --init --recursive
          cd ../../../

          # Verify that hids_client.c is present
          ls -lh Firmware/external/bluepad32/external/btstack/src/ble/gatt-service/hids_client.c

      - name: Create Build and Output Folders
        run: mkdir -p build output

      - name: Build OGX-Mini - ${{ matrix.board }}
        run: |
          cd build
          rm -rf ./*
          cmake -DPICO_SDK_PATH=${{ github.workspace }}/pico-sdk \
                -DCMAKE_BUILD_TYPE=Release \
                -DOGXM_BOARD=${{ matrix.board }} \
                -DMAX_GAMEPADS=1 \
                ../Firmware/RP2040
          cmake --build . -- -j$(nproc)

          # Find and copy the generated .uf2 file
          FILE=$(find . -maxdepth 1 -name "OGX-Mini-*-${{ matrix.board }}*.uf2" | head -n 1)
          cp "$FILE" ../output/

      - name: Upload UF2 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uf2-${{ matrix.board }}
          path: output/*.uf2

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: output

      - name: List Files
        run: ls -lh output/**

      - name: Create Draft Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          tag_name: latest
          draft: true
          files: output/**/*.uf2
