name: Build OGX-Mini

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board:
          - RP2040_ZERO

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Force Recursive Submodules
        run: git submodule update --init --recursive

      - name: Install Dependencies
        run: sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib python3-pycryptodome

      - name: Get Pico SDK
        run: git clone --branch 2.1.0 --recurse-submodules https://github.com/raspberrypi/pico-sdk.git

      - name: Create Build and Output Folders
        run: mkdir -p build output

      - name: Build OGX-Mini - ${{ matrix.board }}
        run: |
          cd build
          rm -rf ./*
          cmake -DPICO_SDK_PATH=${{ github.workspace }}/pico-sdk \
                -DCMAKE_BUILD_TYPE=Release \
                -DOGXM_BOARD=${{ matrix.board }} \
                -DMAX_GAMEPADS=1 \
                ../Firmware/RP2040
          cmake --build .

          FILE=$(find . -maxdepth 1 -name "OGX-Mini-*-${{ matrix.board }}*.uf2" | head -n 1)
          if [ -n "$FILE" ]; then cp "$FILE" ../output/; fi

      - name: Upload UF2 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uf2-${{ matrix.board }}
          path: output/*.uf2
