name: Build OGX-Mini

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board:
          - PI_PICO2W

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Update Nested Submodules Recursively
        run: |
          git submodule update --init --recursive

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib python3-pycryptodome pkg-config libusb-1.0-0-dev

      - name: Get Pico SDK
        run: git clone --branch 2.1.0 --recurse-submodules https://github.com/raspberrypi/pico-sdk.git

      - name: Build & Install Picotool
        run: |
          git clone --branch 2.1.0 https://github.com/raspberrypi/picotool.git
          cd picotool
          mkdir build && cd build
          cmake -DPICO_SDK_PATH=${{ github.workspace }}/pico-sdk ..
          cmake --build . -j$(nproc)
          sudo cmake --install .
          cd ../..
          rm -rf picotool

      - name: Create Build and Output Folders
        run: mkdir -p build output

      - name: Build OGX-Mini - ${{ matrix.board }}
        run: |
          cd build
          rm -rf ./*
          cmake -DPICO_SDK_PATH=${{ github.workspace }}/pico-sdk \
                -DCMAKE_BUILD_TYPE=Release \
                -DOGXM_BOARD=${{ matrix.board }} \
                -DMAX_GAMEPADS=1 \
                ../Firmware/RP2040
          cmake --build . -j$(nproc)

          # Find and copy the generated .uf2 file
          FILE=$(find . -maxdepth 1 -name "OGX-Mini-*-${{ matrix.board }}*.uf2" | head -n 1)
          cp "$FILE" ../output/

      - name: Upload UF2 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uf2-${{ matrix.board }}
          path: output/*.uf2

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: output

      - name: List Files
        run: ls -lh output/**

      - name: Create Draft Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          tag_name: latest
          draft: true
          files: output/**/*.uf2
